/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Entidades.Conta;
import Entidades.GerenciadorContas;
import Entidades.ServerMulti;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author mathe
 */
public class CriaMundoMulti extends javax.swing.JFrame {

    private Conta conta;
    private MultiPlayer telaPai;

    public CriaMundoMulti() {
        initComponents();
    }

    public CriaMundoMulti(Conta conta, MultiPlayer telaPai) {
        this.conta = conta;
        this.telaPai = telaPai;
        initComponents();
        popularListaPlayers();
    }

    private void popularListaPlayers() {
        DefaultListModel<String> model = new DefaultListModel<>();
        List<Conta> todasAsContas = GerenciadorContas.getTodasContas();

        for (Conta c : todasAsContas) {
            if (!c.equals(conta)) {
                model.addElement(c.getNickname());
            }
        }
        listPlayers.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomeMundo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboModo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPlayers = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(492, 516));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setText("Nome do Servidor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 200, 22);

        txtNomeMundo.setBackground(new java.awt.Color(204, 204, 204));
        txtNomeMundo.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        getContentPane().add(txtNomeMundo);
        txtNomeMundo.setBounds(50, 60, 360, 30);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setText("Modo de jogo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 160, 132, 22);

        comboModo.setBackground(new java.awt.Color(204, 204, 204));
        comboModo.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        comboModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sobrevivência", "Criativo", "Hardcore" }));
        getContentPane().add(comboModo);
        comboModo.setBounds(10, 210, 240, 30);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setText("Jogadores convidados");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 110, 230, 22);

        btnSubmit.setBackground(new java.awt.Color(204, 204, 204));
        btnSubmit.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnSubmit.setText("Criar Mundo");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit);
        btnSubmit.setBounds(60, 380, 159, 50);

        btnQuit.setBackground(new java.awt.Color(204, 204, 204));
        btnQuit.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnQuit.setText("Voltar");
        getContentPane().add(btnQuit);
        btnQuit.setBounds(270, 380, 104, 50);

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));

        listPlayers.setBackground(new java.awt.Color(204, 204, 204));
        listPlayers.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        listPlayers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listPlayers);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(270, 150, 180, 180);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nuvens.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-10, 0, 500, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String nomeMundo = txtNomeMundo.getText().trim();
        String modo = (String) comboModo.getSelectedItem();

        if (nomeMundo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o nome do mundo.");
            return;
        }

        List<String> jogadoresSelecionados = listPlayers.getSelectedValuesList();

        ServerMulti novoMundo = new ServerMulti(nomeMundo, modo);
        novoMundo.adicionarProprietario(conta);

        for (String nick : jogadoresSelecionados) {
            Conta jogador = GerenciadorContas.buscarPorNickname(nick);
            if (jogador != null) {
                novoMundo.adicionarProprietario(jogador);
                jogador.adicionarMundoMulti(novoMundo);
            } else {
                JOptionPane.showMessageDialog(this, "Conta " + nick + " não encontrada.");
            }
        }

        conta.adicionarMundoMulti(novoMundo);
        JOptionPane.showMessageDialog(this, "Mundo multiplayer criado!");
        telaPai.depoisCriarMundo();
        this.dispose();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {
        telaPai.setEnabled(true);
        telaPai.toFront();
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriaMundoMulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriaMundoMulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriaMundoMulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriaMundoMulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriaMundoMulti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> comboModo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listPlayers;
    private javax.swing.JTextField txtNomeMundo;
    // End of variables declaration//GEN-END:variables
}
