/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Entidades.Conta;
import Entidades.ServerSingle;
import javax.swing.JOptionPane;
/**
 *
 * @author mathe
 */
public class CriaMundoSingle extends javax.swing.JFrame {
    private Conta conta;
    private SinglePlayer telaPai;
    /**
     * Creates new form CriaMundoSingle
     */
    public CriaMundoSingle() {
       initComponents();
}

    public CriaMundoSingle(Conta conta, SinglePlayer telaPai) {
        this.conta = conta;
        this.telaPai = telaPai;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboModo = new javax.swing.JComboBox<>();
        btnCriar = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(537, 378));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setText("Nome do mundo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 150, 40);

        txtNome.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(110, 60, 340, 30);

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setText("Modo de jogo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 110, 132, 22);

        comboModo.setBackground(new java.awt.Color(204, 204, 204));
        comboModo.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        comboModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sobrevivência", "Criativo", "Hardcore" }));
        comboModo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(comboModo);
        comboModo.setBounds(130, 150, 250, 32);

        btnCriar.setBackground(new java.awt.Color(204, 204, 204));
        btnCriar.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnCriar.setText("Criar mundo");
        btnCriar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCriar);
        btnCriar.setBounds(120, 230, 140, 50);

        btnQuit.setBackground(new java.awt.Color(204, 204, 204));
        btnQuit.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnQuit.setText("Sair");
        btnQuit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(btnQuit);
        btnQuit.setBounds(300, 230, 80, 50);

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nuvens.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, 0, 550, 380);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        String nomeMundo = txtNome.getText().trim();
        String modo = (String) comboModo.getSelectedItem();
        if (nomeMundo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o nome do mundo.");
            return;
        }

        ServerSingle novoMundo = new ServerSingle(nomeMundo, modo, conta);
        conta.adicionarMundoSing(novoMundo);
       

        JOptionPane.showMessageDialog(this, "Mundo criado com sucesso!");
        telaPai.depoisCriarMundo();
        this.dispose();
    }//GEN-LAST:event_btnCriarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {
        telaPai.setEnabled(true);
        telaPai.toFront();
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriaMundoSingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriaMundoSingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriaMundoSingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriaMundoSingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriaMundoSingle().setVisible(true);
            }
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnQuit;
    private javax.swing.JComboBox<String> comboModo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
