/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Entidades.Conta;
import Entidades.GerenciadorContas;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author mathe
 */
public class TelaInicial extends javax.swing.JFrame {
    private Conta contaLogada;
  
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }
    
    public TelaInicial(Conta conta){
        this.contaLogada = conta;
        initComponents();
        this.setTitle("Minecrat - logado como " + contaLogada.getNickname());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSingle = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1119, 661));
        getContentPane().setLayout(null);

        btnSingle.setBackground(new java.awt.Color(204, 204, 204));
        btnSingle.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnSingle.setText("SINGLEPLAYER");
        btnSingle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingleActionPerformed(evt);
            }
        });
        getContentPane().add(btnSingle);
        btnSingle.setBounds(290, 220, 463, 60);

        btnMulti.setBackground(new java.awt.Color(204, 204, 204));
        btnMulti.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnMulti.setText("MULTIPLAYER");
        btnMulti.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });
        getContentPane().add(btnMulti);
        btnMulti.setBounds(290, 310, 463, 60);

        btnSettings.setBackground(new java.awt.Color(204, 204, 204));
        btnSettings.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnSettings.setText("SETTINGS");
        btnSettings.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSettings);
        btnSettings.setBounds(530, 410, 230, 60);

        btnQuit.setBackground(new java.awt.Color(204, 204, 204));
        btnQuit.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnQuit.setText("QUIT GAME");
        btnQuit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuit);
        btnQuit.setBounds(290, 410, 225, 60);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("MINECRAFT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 70, 290, 140);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Minecraft 1.21.6");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 640, 129, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telaprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-730, -130, 1980, 1260);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        MultiPlayer mtp = new MultiPlayer(contaLogada);
        mtp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        List<Conta> todasAsContas = GerenciadorContas.getTodasContas();
        
        Login lo = new Login((ArrayList<Conta>) todasAsContas);
        lo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        Settings set = new Settings();
        set.setVisible(true);
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingleActionPerformed
        SinglePlayer sngp = new SinglePlayer(contaLogada);
        sngp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSingleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnSingle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
